
web:
    # 指定image
    #image: johnny/docker-hello
    # 执行的命令
    #command: /bin/bash
    ports:
         - "80:80"
    # 卷
    # volumes:
        # -.:figapp
    links:
         - mongo
    # 指定编译目录，会编译 . 目录下面的 Dockerfile
    build: .

mongo:
    #image: johnny/mongo
    ports:
         - "27017:27017"
    build: ./mongo
